### ISSUE TITLE
Inquiry about code issue: Unrecognized variable or object in cmot_functions.py

### ISSUE THREAD

**Issue by qiongyusheng** [sayali7/CMOT#3]
I'd like to express my gratitude for the outstanding work you've done. I firmly believe that CMOT is an excellent method for modal inference.

However, as I attempted to follow the provided tutorial to run the program, I encountered what seems to be an issue with the code. Upon inspection, I noticed an unfamiliar variable or object, "snpXTest," at line 59 in the cmot_functions.py file. It appears that this undefined object is causing the code to malfunction, preventing it from running correctly.

I'm reaching out to kindly request your assistance in resolving this matter. Any guidance or clarification you could provide regarding the variable or object "snpXTest," its intended purpose, or any dependencies required for its proper definition would be greatly appreciated.

Regards,
QY

**Comment by sayali7** [comment]
Hi QY,

Thank you for using our code and pointing out the error. I apologize for the delayed response. The issue has now been resolved.
